name: "APAX Decoupled Drupal Recipe"
description: "A Drupal 11 recipe for extending the apax/recipe_apax_base recipe with additional Drupal modules and configurations for a decoupled Drupal setup."
type: "Site"

recipes:
  - recipe_apax_base

install:
  - decoupled_preview_iframe
  - graphql_compose
  - graphql_compose_edges
  - graphql_compose_fragments
  - graphql_compose_image_style
  - graphql_compose_menus
  - graphql_compose_preview
  - graphql_compose_routes
  - graphql_compose_users
  - graphql_compose_views
  - simple_oauth
  - view_unpublished
  - visual_editor

config:
  import:
    decoupled_preview_iframe: "*"
    graphql_compose: "*"
    graphql_compose_edges: "*"
    graphql_compose_fragments: "*"
    graphql_compose_image_style: "*"
    graphql_compose_menus: "*"
    graphql_compose_preview: "*"
    graphql_compose_routes: "*"
    graphql_compose_users: "*"
    graphql_compose_views: "*"
    simple_oauth: "*"
    view_unpublished: "*"
    visual_editor: "*"

  actions:
    # Set the preview types and draft provider for the decoupled preview iframe.
    decoupled_preview_iframe.settings:
      simpleConfigUpdate:
        draft_provider: graphql_compose_preview
        preview_types:
          node:
            page: page
    # Set the Simple OAuth settings.
    simple_oauth.settings:
      simpleConfigUpdate:
        access_token_expiration: 2592000
        authorization_code_expiration: 2592000
        refresh_token_expiration: 2592000
        remember_clients: true
        use_implicit: false
        public_key: ../keys/public.key
        private_key: ../keys/private.key

    # Set user roles and permissions.
    user.role.anonymous:
      grantPermissions:
        - execute graphql_compose_server arbitrary graphql requests
    user.role.viewer:
      createIfNotExists:
        id: viewer
        label: Viewer
        weight: -8
      grantPermissions:
        - execute graphql_compose_server arbitrary graphql requests
    user.role.previewer:
      createIfNotExists:
        id: previewer
        label: Previewer
        weight: -7
      grantPermissions:
        - execute graphql_compose_server arbitrary graphql requests
        - view all revisions
        - view any unpublished content
        - view graphql_compose_preview entity
        - view own unpublished content